---
AWSTemplateFormatVersion: '2010-09-09'
Description: Stack managing begin and end of business hours instance actions

Parameters:

  Account:
    Description: Account
    Type: String
    Default: dev
    AllowedValues:
    - dev
    - recprod
  TagBloc:
    Description: Tag bloc metier
    Type: String
    Default: operations
  TagApp:
    Description: Tag application
    Type: String
    Default: hypnos
  TagComp:
    Description: Tag composants
    Type: String
    Default: application
  CronBeginBusinessHours:
    Description: Hour to wake up infrastructure
    Type: String
    Default: "cron(0 7 ? * MON-FRI *)"
  CronEndBusinessHours:
    Description: Hour to stop infrastructure
    Type: String
    Default: "cron(0 19 ? * MON-FRI *)"

Mappings:

  AccountMap:
    dev:
      LambdaS3Bucket: "applications.dev"
    recprod:
      LambdaS3Bucket: "applications.rec"

Resources:

  HypnosLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: operations-hypnos-access
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: "lambda.amazonaws.com"
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: instances-management-allow
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - logs:PutLogEvents
            - logs:CreateLogGroup
            - logs:CreateLogStream
            Resource:
            - "arn:aws:logs:*:*:*"
          - Effect: Allow
            Action:
            - ec2:DescribeInstances
            - autoscaling:DescribeAutoScalingGroups
            Resource:
            - "*"
          - Effect: Allow
            Action:
            - ec2:TerminateInstances
            Resource:
            - "arn:aws:ec2:*:*:instance/*"
          - Effect: Allow
            Action:
            - autoscaling:ResumeProcesses
            - autoscaling:SetDesiredCapacity
            - autoscaling:UpdateAutoScalingGroup
            - autoscaling:SuspendProcesses
            Resource:
            - !Sub 'arn:aws:autoscaling:${AWS::Region}:${AWS::AccountId}:autoScalingGroup:*:autoScalingGroupName/*'

  HypnosLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties: 
      LogGroupName: !Sub '/aws/lambda/${TagBloc}-${TagApp}-${Account}' 
      RetentionInDays: 30

  HypnosLambda:
    Type: "AWS::Lambda::Function"
    Properties: 
      Code:
        S3Bucket: !FindInMap [AccountMap, !Ref Account, LambdaS3Bucket]
        S3Key: "hypnos/hypnos-terminate.py.zip"
      Description: "Manage instance during non business hours"
      FunctionName: !Sub '${TagBloc}-${TagApp}-${Account}'
      Handler: "hypnos-terminate.lambda_handler"
      MemorySize: 128
      Role: !Sub ${HypnosLambdaRole.Arn}
      Runtime: "python3.6"
      Timeout: 60
      Tags:
      - Key: Env
        Value: !Ref Account
      - Key: Bloc
        Value: !Ref TagBloc
      - Key: Comp
        Value: !Ref TagComp
      - Key: App
        Value: !Ref TagApp

  EndOfBusinessHoursEventRule:
    Type: "AWS::Events::Rule"
    Properties: 
      Description: "Start of non-business hours actions"
      Name: !Sub '${TagBloc}-${TagApp}-start-nonbusinesshours-${Account}'
      ScheduleExpression: !Ref CronEndBusinessHours
      State: "ENABLED"
      Targets:
      - Arn: !Sub ${HypnosLambda.Arn}
        Id: BeginningOfNonBusinessHoursEventRule
        Input : '{ "action": "stop" }'

  PermissionForEndBusinessHoursToInvokeLambda:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref HypnosLambda
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !Sub ${EndOfBusinessHoursEventRule.Arn}

  BeginOfBusinessHoursEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: "End of non-business hours actions"
      Name: !Sub '${TagBloc}-${TagApp}-end-nonbusinesshours-${Account}'
      ScheduleExpression: !Ref CronBeginBusinessHours
      State: "ENABLED"
      Targets:
      - Arn: !Sub ${HypnosLambda.Arn}
        Id: BeginBusinessHoursEventRule
        Input : '{ "action": "start" }'

  PermissionForBeginBusinessHoursToInvokeLambda:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref HypnosLambda
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !Sub ${BeginOfBusinessHoursEventRule.Arn}

